repos:
  - repo: https://github.com/fredrikekre/runic-pre-commit
    rev: v2.2.0
    hooks:
      - id: runic
        args: ["--check", "--diff"]
        additional_dependencies:
          # Keep in sync with .github/workflows/Format.yml
          - "Runic@1.11.1"
