steps:
  - label: "CUDA Julia v{{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
          - "1.11"
          - "1.12"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1: ~
    agents:
      queue: "cuda"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
    commands: |
      echo "--- Setup Julia packages"
      JULIA_PKG_PRECOMPILE_AUTO="false" julia --color=yes -e '
          using Pkg
          pkgs = [PackageSpec(; path) for path in (".", "lib/EnzymeCore", "lib/EnzymeTestUtils")]
          Pkg.develop(pkgs)
          Pkg.add([PackageSpec(; name="CUDA", version="6"), PackageSpec(; name = "MetaTesting", version = "0.1.0")])' || exit 3

      echo "+++ Run tests"
      julia --color=yes --code-coverage=@ test/cuda.jl
      julia --color=yes --code-coverage=@ lib/EnzymeTestUtils/test/cuda_to_vec.jl
      julia --color=yes --code-coverage=@ lib/EnzymeTestUtils/test/cuda_test_reverse.jl
      julia --color=yes --code-coverage=@ lib/EnzymeTestUtils/test/cuda_test_forward.jl
    env:
      JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager

#   - label: "AMDGPU Julia v{{matrix.version}}"
#     matrix:
#       setup:
#         version:
#           - "1.10"
#     plugins:
#       - JuliaCI/julia#v1:
#           version: "{{matrix.version}}"
#     agents:
#       queue: "rocm"
#     if: build.message !~ /\[skip tests\]/
#     timeout_in_minutes: 60
#     commands: |
#       echo "--- Setup Julia packages"
#       julia --color=yes -e '
#           using Pkg
#           pkgs = [PackageSpec(; path) for path in (".", "lib/EnzymeCore", "lib/EnzymeTestUtils")]
#           push!(pkgs, PackageSpec(; name="AMDGPU"))
#           Pkg.develop(pkgs)' || exit 3
# 
#       echo "+++ Run tests"
#       julia --color=yes test/amdgpu.jl
#     env:
#       JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
# 
  - label: "Metal Julia v{{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
          - "1.11"
          - "1.12"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1: ~
    agents:
      queue: "metal"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
    commands: |
      echo "--- Setup Julia packages"
      julia --color=yes -e '
          using Pkg
          pkgs = [PackageSpec(; path) for path in (".", "lib/EnzymeCore", "lib/EnzymeTestUtils")]
          Pkg.develop(pkgs)
          Pkg.add([PackageSpec(; name="Metal")])' || exit 3

      echo "+++ Run tests"
      julia --color=yes --code-coverage=@ test/metal.jl
    env:
      JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager

env:
  SECRET_CODECOV_TOKEN: "qoiDkcckne4jd2/uA0uVRnr0a+lt89H/8VwHVSrbrfs1gnMVCsuoIQ7VKHbRXoqm4smR2qDQF0C2yu/n8YmTohd5lgJryuil63FCP4RTfdtW2kR6QV6wi26+JpKZ7tXvHiQFXAby8YhLg/2RAn+y0B5vR9iXvkpCkfSIFdXPUmBrY5cBs1YwONRrOsLQY8E7UkD5mdg80OKT2eaUq26QSb1ipns6yFOT361GDiAl9B1Nm1/GEN7KZN9nN37ATcHnMWnALyHmvzYa2aux3pTr3tDCAUxejGR+SqxjWjJ4RA1zZE1106a58d5PzX8v0vq0Q+NMeZCCa/65igEbt94uEw==;U2FsdGVkX1/qp2mNLgVWtBzevIGK9yhebLzdHlo4LmMkpFk4A4k9BYM9pIg8nYg6taxno0LH6Q8QfDg12EmfGQ=="
